name: "Upload Release Assets"

# Controls when the action will run.
on:
  workflow_call:

permissions:
  contents: write


jobs:
  UploadAssets:
    name: Upload Assets
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    env:
      firmware_zip: 'Roast Meter BLE Firmware-${{ github.ref_name }}.zip'

    steps:
      - id: download
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - id: zip_firmware
        run: zip -r -5 '${{ env.firmware_zip }}' .
      
      - id: upload_assets
        name: Upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.firmare_zip }}
          generate_release_notes: false